name: langaw
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.5.0
  flame_audio: ^1.4.0
  audioplayers: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # 리소스 정보를 추가한다. (이미지...)
  assets:
    - assets/images/bg/
    - assets/images/ui/
    - assets/images/branding/
    - assets/images/flies/
    - assets/audio/sfx/
    - assets/audio/bgm/
